[buildPlans.iosevka-hololight]
family = "Iosevka Hololight"
spacing = "term"
serifs = "sans"
no-cv-ss = false

[buildPlans.iosevka-hololight.variants.design]
capital-a = "straight-serifless"
a = "single-storey-serifless"
i = "serifed"
y = "cursive"
zero = "slashed"
one = "nobase"
two = "curly-neck"
three = "twoarcs"
four = "semi-open"
asterisk = "penta-low"
underscore = "high"
paragraph-sign = "high"
caret = "medium"
brace = "straight"
ampersand = "closed"
at = "fourfold"
dollar = "through"
cent = "through"
percent = "rings-continuous-slash"
bar = "natural-slope"

[buildPlans.iosevka-hololight.widths.normal]
shape = 600
menu = 5
css = "normal"