[buildPlans.iosevka-hololight]
family = "Iosevka Hololight"
spacing = "normal"
serifs = "slab"
no-cv-ss = false

[buildPlans.iosevka-hololight.variants.design]
capital-a = "straight-serifless"
capital-g = "toothless-rounded-serifless-hooked"
capital-i = "short-serifed"
capital-m = "hanging"
capital-r = "standing"
capital-s = "bilateral-inward-serifed"
a = "single-storey-earless-corner-serifless"
b = "toothless-corner"
d = "toothless-corner-serifless"
e = "flat-crossbar"
f = "flat-hook"
g = "earless-corner"
i = "hooky"
l = "tailed"
m = "normal"
p = "earless-corner"
q = "earless-corner"
r = "serifed"
s = "bilateral-inward-serifed"
u = "toothless-corner"
y = "cursive"
cyrl-capital-ya = "standing"
cyrl-ya = "standing-tailed"